version: '3.7'

services:
  nginx:
    image: jwilder/nginx-proxy:latest
    hostname: nginx
    depends_on:
      - mcweb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/mcweb.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - default

  mcweb:
    image: mcweb:latest
    hostname: mcweb
    networks:
      default:
        aliases:
          - mcweb
          - mcweb.test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - type: volume
        source: instruments
        target: /srv/mcweb/McWeb/mcsimrunner/sim
    extra_hosts:
      - "mcweb.test:127.0.0.1"
#    command: "/srv/mcweb/McWeb/scripts/docker-entry.sh"

volumes:
  instruments:
    driver_opts:
      type: none
      device: $PWD/bootstrap_data/instruments
      o: bind

networks:
  default:
    attachable: True
