version: '3.7'

services:
  nginx:
    image: jwilder/nginx-proxy:latest
    hostname: nginx
    depends_on:
      - mcweb
    ports:
      - "80:80"
      - "443:443"
#       - "8080:8080"
#       - "8000:8000"
    volumes:
#      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/mcweb.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - default

  mcweb:
    image: mcweb:latest
    hostname: mcweb
    ports:
      - "2222:2222"
    networks:
      default:
        aliases:
          - mcweb
          - mcweb.test
    extra_hosts:
      - "mcweb.test:127.0.0.1"

networks:
  default:
    attachable: True
