version: '3.7'

services:
# An Nginx proxy can be setup using the following definitions.
#  nginx:
#    image: jwilder/nginx-proxy:latest
#    hostname: nginx
#    depends_on:
#      - mcweb
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/mcweb.conf:ro
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#    networks:
#      - default

  mcweb:
    image: nielsbohr/mcweb:latest
    hostname: mcweb
    # If an nginx proxy is used, the port section below should be commented out.
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        aliases:
          - mcweb
          - mcweb.test
    volumes:
      - type: volume
        source: instruments
        target: /srv/mcweb/McWeb/mcsimrunner/sim
      - type: volume
        source: data
        target: /srv/mcweb/McWeb/mcsimrunner/static/data
    configs:
      - source: aws_config
        target: /var/www/.aws/config
        uid: '33'
        gid: '33'
        mode: 0440
      - source: oci_config
        target: /var/www/.oci/config
        uid: '33'
        gid: '33'
        mode: 0440
      - source: corc_config
        target: /var/www/.corc/config
        uid: '33'
        gid: '33'
        mode: 0440
    secrets:
      - source: aws_credentials
        target: /var/www/.aws/credentials
        uid: '33'
        gid: '33'
        mode: 0440
      - source: oci_private_key
        target: /var/www/.oci/oci_api_key.pem
        uid: '33'
        gid: '33'
        mode: 0440
      - source: oci_public_key
        target: /var/www/.oci/oci_api_key_public.pem
        uid: '33'
        gid: '33'
        mode: 0440
    environment:
      - CORC_CONFIG_FILE='/var/www/.corc/config'
      - OCI_CONFIG_FILE='/var/www/.oci/config'

volumes:
  instruments:
    driver_opts:
      type: none
      device: $PWD/bootstrap_data/instruments
      o: bind
  data:
    driver_opts:
      type: none
      device: $PWD/bootstrap_data/simrun_data
      o: bind

networks:
  default:
    attachable: True

configs:
  aws_config:
    file: ./configs-platform/.aws/config
  oci_config:
    file: ./configs-platform/.oci/config
  corc_config:
    file: ./configs-platform/.corc/config

secrets:
  aws_credentials:
    file: ./configs-platform/.aws/credentials
  oci_private_key:
    file: ./configs-platform/.oci/oci_api_key.pem
  oci_public_key:
    file: ./configs-platform/.oci/oci_api_key_public.pem
