version: '3.7'

services:
  nginx:
    image: nginx:latest
    hostname: patches-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - patches-network
    restart: always

  mcweb:
    image: patchesmcweb:latest
    hostname: patches-mcweb
    depends_on:
      - nginx
    networks:
      patches-network:
        aliases:
          - mcweb
          - mcweb.test
    extra_hosts:
      - "mcweb.test:127.0.0.1"

networks:
  patches-network:
    attachable: True
