version: '3.7'

services:
  nginx:
    image: jwilder/nginx-proxy:latest
    hostname: nginx
    depends_on:
      - mcweb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/mcweb.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - default

  mcweb:
    image: mcweb:latest
    hostname: mcweb
    networks:
      default:
        aliases:
          - mcweb
          - mcweb.test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - type: volume
        source: instruments
        target: /srv/mcweb/McWeb/mcsimrunner/sim
    configs:
      - source: aws_config
        target: /www-data/.aws/config
        mode: 0440
      - source: oci_config
        target: /www-data/.oci/config
        mode: 0440
      - source: corc_config
        target: /www-data/.corc/config
        mode: 0440
    secrets:
      - source: aws_credentials
        target: /www-data/.aws/credentials
        mode: 0440
      - source: oci_private_key
        target: /www-data/.oci/oci_api_key.pem
        mode: 0440
      - source: oci_public_key
        target: /www-data/.oci/oci_api_key_public.pem
        mode: 0440
    extra_hosts:
      - "mcweb.test:127.0.0.1"

volumes:
  instruments:
    driver_opts:
      type: none
      device: $PWD/bootstrap_data/instruments
      o: bind

networks:
  default:
    attachable: True

configs:
  aws_config:
    file: ./configs-platform/.aws/config
  oci_config:
    file: ./configs-platform/.oci/config
  corc_config:
    file: ./configs-platform/.corc/config

secrets:
  aws_credentials:
    file: ./configs-platform/.aws/credentials
  oci_private_key:
    file: ./configs-platform/.oci/oci_api_key.pem
  oci_public_key:
    file: ./configs-platform/.oci/oci_api_key_public.pem