version: '3.7'

services:
  mcweb:
    image: patchesmcweb
    hostname: mcweb-test
    environment:
      TZ: Europe/Copenhagen
    ports:
      - "8080:8080"
    networks:
      default:
        aliases:
          - www.mcweb.test
          - mcweb.test
          - mcweb
    extra_hosts:
      - "mcweb.test:127.0.0.1"
    volumes:
      - type: volume
        source: certs
        target: /etc/httpd/mc-certificates

  nginx-proxy:
    hostname: nginx-reverse-proxy
    image: jwilder/nginx-proxy
    depends_on:
      - mcweb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.config/mcweb-test.conf:/etc/nginx/conf.d/mcweb-test.conf:ro

volumes:
  conf:
    driver_opts:
      type: none
      device: $PWD/nginx.config
      o: bind
  certs:
    driver_opts:
      type: none
      device: $PWD/certs
      o: bind
